import type {
  ConversationTurn,
  LearnerState,
  LearningThread,
  Preferences,
  SourceDocument,
  VocabularyItem,
} from "@/lib/types";
import { DEFAULT_CONVERSATION_ID } from "@/lib/conversation-context";

const now = new Date();
const inDays = (days: number) => new Date(now.getTime() + days * 86_400_000).toISOString();

export const seedVocabulary: VocabularyItem[] = [
  {
    id: "v-maqam",
    lemma: "مقام",
    vocalized: "مَقَامٌ",
    root: "ق و م",
    sense: "A spiritual station reached through disciplined wayfaring",
    englishGloss: "station; standing-place",
    technicalGloss: "a relatively established station on the spiritual path",
    register: "classical",
    status: "learning",
    comprehension: 0.91,
    production: 0.58,
    automaticity: 0.42,
    uncertainty: 0.18,
    retentionHalfLifeDays: 4.5,
    contextCount: 2,
    successfulDelayedUse: false,
    nextReview: inDays(1),
    sourceRelevance: 1,
    discussionUtility: 0.93,
    collocations: ["مَقَامُ التَّوْبَةِ", "بَلَغَ مَقَامًا"],
    examples: ["لِكُلِّ مَقَامٍ مَعْنًى يَخْتَصُّ بِهِ."],
    sourceLabel: "مَنَازِلُ السَّائِرِينَ",
  },
  {
    id: "v-hal",
    lemma: "حال",
    vocalized: "حَالٌ",
    root: "ح و ل",
    sense: "A passing spiritual state or condition",
    englishGloss: "state; condition",
    technicalGloss: "a state experienced by the heart, often contrasted with مَقَام",
    register: "classical",
    status: "to_acquire",
    comprehension: 0.66,
    production: 0.24,
    automaticity: 0.18,
    uncertainty: 0.31,
    retentionHalfLifeDays: 1.4,
    contextCount: 1,
    successfulDelayedUse: false,
    nextReview: inDays(0),
    sourceRelevance: 0.96,
    discussionUtility: 0.86,
    collocations: ["حَالُ الْقَلْبِ", "يَطْرَأُ عَلَيْهِ حَالٌ"],
    examples: ["الْحَالُ يَتَغَيَّرُ، أَمَّا الْمَقَامُ فَأَثْبَتُ."],
    sourceLabel: "لُغَةُ التَّزْكِيَةِ",
  },
  {
    id: "v-tazkiya",
    lemma: "تزكية",
    vocalized: "تَزْكِيَةٌ",
    root: "ز ك و",
    sense: "Purification joined with growth and cultivation",
    englishGloss: "purification; cultivation",
    technicalGloss: "purification and growth of the soul",
    register: "classical",
    status: "mastered",
    comprehension: 0.96,
    production: 0.9,
    automaticity: 0.83,
    uncertainty: 0.08,
    retentionHalfLifeDays: 28,
    contextCount: 5,
    successfulDelayedUse: true,
    nextReview: inDays(12),
    sourceRelevance: 0.9,
    discussionUtility: 0.85,
    collocations: ["تَزْكِيَةُ النَّفْسِ", "يُزَكِّي نَفْسَهُ"],
    examples: ["تَزْكِيَةُ النَّفْسِ تَجْمَعُ بَيْنَ التَّخْلِيَةِ وَالتَّحْلِيَةِ."],
    sourceLabel: "مَجَالِسُ التَّزْكِيَةِ",
  },
  {
    id: "v-yabdu",
    lemma: "يبدو لي أن",
    vocalized: "يَبْدُو لِي أَنَّ",
    root: "ب د و",
    sense: "A measured way to introduce one’s interpretation",
    englishGloss: "it seems to me that",
    register: "formulaic",
    status: "learning",
    comprehension: 0.84,
    production: 0.61,
    automaticity: 0.49,
    uncertainty: 0.19,
    retentionHalfLifeDays: 5.2,
    contextCount: 2,
    successfulDelayedUse: false,
    nextReview: inDays(2),
    sourceRelevance: 0.72,
    discussionUtility: 0.98,
    collocations: ["يَبْدُو لِي أَنَّ الْمُؤَلِّفَ", "يَبْدُو لِي مِنَ السِّيَاقِ"],
    examples: ["يَبْدُو لِي أَنَّ الْمَقْصُودَ أَدَقُّ مِنْ ذٰلِكَ."],
    sourceLabel: "عِبَارَاتُ الْمَجْلِسِ",
  },
  {
    id: "v-maa-anna",
    lemma: "مع أن",
    vocalized: "مَعَ أَنَّ",
    root: "م ع",
    sense: "Introduces a concession before a contrasting point",
    englishGloss: "although; despite the fact that",
    register: "formulaic",
    status: "to_acquire",
    comprehension: 0.54,
    production: 0.19,
    automaticity: 0.14,
    uncertainty: 0.35,
    retentionHalfLifeDays: 1,
    contextCount: 0,
    successfulDelayedUse: false,
    nextReview: inDays(0),
    sourceRelevance: 0.6,
    discussionUtility: 0.91,
    collocations: ["مَعَ أَنَّ هٰذَا صَحِيحٌ", "مَعَ أَنِّي أُوَافِقُهُ"],
    examples: ["مَعَ أَنَّ الْعِبَارَةَ قَصِيرَةٌ، فَمَعْنَاهَا وَاسِعٌ."],
    sourceLabel: "عِبَارَاتُ الْمَجْلِسِ",
  },
];

export const seedCompetencies: LearnerState[] = [
  ["c-listen", "listening", "Following the main idea", "فَهْمُ الْفِكْرَةِ", "listening_comprehension", 0.38, 0.24, 0.31],
  ["c-vocab", "vocabulary", "Activating vocabulary", "اِسْتِحْضَارُ الْمُفْرَدَاتِ", "spontaneous_production", 0.32, 0.2, 0.27],
  ["c-summary", "summarization", "Summarizing faithfully", "تَلْخِيصُ الْمَعْنَى", "spontaneous_production", 0.35, 0.29, 0.3],
  ["c-discourse", "discourse_management", "Keeping the discussion moving", "إِدَارَةُ الْحِوَارِ", "spontaneous_production", 0.29, 0.3, 0.24],
  ["c-grammar", "grammar", "Grammar recognition", "فَهْمُ النَّحْوِ", "reading_recognition", 0.82, 0.16, 0.58],
  ["c-production", "grammar", "Grammar in live speech", "النَّحْوُ فِي الْكَلَامِ", "spontaneous_production", 0.46, 0.31, 0.35],
  ["c-fidelity", "source_fidelity", "Source fidelity", "أَمَانَةُ النَّقْلِ", "meaning_recall", 0.58, 0.28, 0.43],
].map(([competencyId, domain, label, arabicLabel, mode, mastery, uncertainty, automaticity]) => ({
  competencyId: competencyId as string,
  domain: domain as LearnerState["domain"],
  label: label as string,
  arabicLabel: arabicLabel as string,
  mode: mode as LearnerState["mode"],
  masteryProbability: mastery as number,
  uncertainty: uncertainty as number,
  automaticity: automaticity as number,
  retentionHalfLifeDays: 7,
  contextCount: 2,
  medianRetrievalLatencyMs: 2800,
  nextReview: inDays(1),
}));

export const seedThreads: LearningThread[] = [
  {
    id: "thread-opinion",
    conversationId: DEFAULT_CONVERSATION_ID,
    triggerSignalId: "seed-signal",
    kind: "construction",
    learnerGoal: "Express an interpretation without sounding absolute",
    targetArabic: "يَبْدُو لِي أَنَّ…",
    relatedCompetencies: ["c-discourse", "c-vocab"],
    relatedPassages: ["passage-1"],
    priority: 0.86,
    status: "active",
    lastLearnerInterestAt: now.toISOString(),
    successfulUses: 1,
    sourceBridge: "Use it to introduce your understanding of the distinction between مَقَام and حَال.",
  },
  {
    id: "thread-concession",
    conversationId: DEFAULT_CONVERSATION_ID,
    triggerSignalId: "seed-signal-2",
    kind: "construction",
    learnerGoal: "Make a respectful contrast",
    targetArabic: "مَعَ أَنَّ… فَإِنَّ…",
    relatedCompetencies: ["c-discourse", "c-production"],
    relatedPassages: [],
    priority: 0.63,
    status: "bookmarked",
    lastLearnerInterestAt: inDays(-1),
    successfulUses: 0,
  },
];

export const seedSources: SourceDocument[] = [
  {
    id: "source-manazil",
    title: "مَنَازِلُ السَّائِرِينَ",
    author: "عَبْدُ اللهِ الْأَنْصَارِيُّ الْهَرَوِيُّ",
    genre: "tazkiya",
    edition: "Personal study excerpt",
    createdAt: now.toISOString(),
    passages: [
      {
        id: "passage-1",
        documentId: "source-manazil",
        sequence: 1,
        arabic: "مَقْطَعٌ تَدْرِيبِيٌّ: الْمَقَامُ مَعْنًى يَثْبُتُ بِالْمُمَارَسَةِ، وَالْحَالُ مَعْنًى يَطْرَأُ عَلَى الْقَلْبِ ثُمَّ يَتَغَيَّرُ.",
        citationLabel: "Illustrative language prompt — not a quotation from the work",
        isDirectQuote: false,
        concepts: ["مَقَام", "حَال", "السُّلُوك"],
      },
    ],
  },
];

export const seedTurns: ConversationTurn[] = [
  {
    id: "turn-welcome",
    conversationId: DEFAULT_CONVERSATION_ID,
    role: "tutor",
    arabic: "أَهْلًا بِكَ. لِنَبْدَأْ بِفِكْرَةٍ صَغِيرَةٍ: مَا الْفَرْقُ بَيْنَ الْمَقَامِ وَالْحَالِ فِي فَهْمِكَ؟",
    english: "Welcome. Let us begin with one small idea: what is the difference between a station and a state in your understanding?",
    glosses: [
      { arabic: "أَهْلًا", english: "welcome" },
      { arabic: "بِكَ", english: "to you" },
      { arabic: "لِنَبْدَأْ", english: "let us begin", root: "ب د أ" },
      { arabic: "بِفِكْرَةٍ", english: "with an idea", root: "ف ك ر" },
      { arabic: "صَغِيرَةٍ", english: "small", root: "ص غ ر" },
      { arabic: "مَا", english: "what" },
      { arabic: "الْفَرْقُ", english: "the difference", root: "ف ر ق" },
      { arabic: "بَيْنَ", english: "between" },
      { arabic: "الْمَقَامِ", english: "the station", root: "ق و م" },
      { arabic: "وَالْحَالِ", english: "and the state", root: "ح و ل" },
      { arabic: "فِي", english: "in" },
      { arabic: "فَهْمِكَ", english: "your understanding", root: "ف ه م" },
    ],
    createdAt: now.toISOString(),
    sourceStatus: "illustrative_only",
  },
];

export const seedPreferences: Preferences = {
  sessionMinutes: 20,
  majlisShare: 0.5,
  glossMode: "tap",
  engagementAdaptation: true,
  explicitExplanations: false,
  voice: "cedar",
};
